print('spam eggs')
print('doesn\'t')
print("doesn't")
print('"Yes", he said')
print("\"Yes\", he said")
print('C:\some\name')
print(r'C:\some\name')
print(2 * 'Peter ' + 'Colt')
print('Darko ' 'Stefanovic')
word = 'Python'
print(word[0])
print(word[5])
print(word[-1])
print(word[-2])
print(word[3:])
print(word[:3])
print(word[1:4])
